//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlitterTweeting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Follow
    {
        public System.Guid ID { get; set; }
        public System.Guid Follower_UserID { get; set; }
        public System.Guid Followed_UserID { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
