//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlitterTweeting.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tag
    {
        public System.Guid ID { get; set; }
        public System.Guid TweetID { get; set; }
        public string TagName { get; set; }
        public Nullable<int> SearchCount { get; set; }
    
        public virtual Tweet Tweet { get; set; }
        public virtual Tweet Tweet1 { get; set; }
    }
}
